name: Sample Workflow

#This is the logic to trigger the workflow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

# This is section where the steps GitHub Actions workflow file.
jobs:       
    run:
        name: Run Sample Script
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Run the script
              run: |
                echo "Running the script..."
                # Add your script commands here
                echo "Script completed."
    
    test:
        name: Run test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Run the test
              run: |
                echo "Running the test..."
                # Add your test commands here
                echo "Test completed."